version: "3.6"

services:
    db:
        image: mysql:5.7.26
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        network_mode: host
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: stacke
            MYSQL_USER: user
            MYSQL_PASSWORD: password

        volumes:
            - ./dev/init:/docker-entrypoint-initdb.d

    # server:
    #     image: snimmagadda/stack-exchange-graphql-server:latest
    #     network_mode: host
    #     environment:
    #         MYSQL_ROOT_PASSWORD: password
    #         MYSQL_DATABASE: stacke
    #         MYSQL_USER: user
    #         MYSQL_PASSWORD: password

    adminer:
        image: adminer
        restart: always
        depends_on:
            - db
        ports:
            - 8080:8080
